backend:
  name: git-gateway
local_backend: true

media_folder: "static/uploads/"
public_folder: "/uploads/"

collections:
  #######################################################
  ## Laws
  #######################################################
  - label: "Data"
    name: "data"
    editor: { preview: false }
    files:
      - label: "Laws"
        name: "laws"
        file: "_data/laws.yml"
        fields:
          - label: "Laws"
            name: "entries"
            widget: "list"
            default: []
            summary: "{{name}}"
            fields:
              # Identifier
              - label: "Identifier"
                name: "slug"
                widget: "string"
                required: true
                pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Must be a valid slug! e.g: bill-of-rights"]
                hint: "This identifies the law and so should reflect the purpose of the law, e.g: bill-of-rights"
              # Short Title
              - label: "Short Title"
                name: "name"
                widget: "string"
                required: true
                hint: "The shorter version of the piece of law, e.g: Constitution of Icenia"
              # Long Title (optional)
              - label: "Full Title"
                name: "fullname"
                widget: "string"
                required: false
                hint: "The full name of the piece of legislation, e.g: The Constitution of the Third Republic of Icenia. Leave empty if unnecessary."
              # Type of law
              - label: "Category"
                name: "kind"
                widget: "select"
                required: true
                hint: "The type of law this legislation is classed as."
                options:
                  - {label: "Statute / Ordinary Law", value: "statute"}
                  - {label: "Constitutional Law", value: "constitution"}
                  - {label: "Incorporation of Statehood", value: "statehood"}
                  - {label: "Treaty", value: "treaty"}
              # Google Doc
              - label: "Google Doc"
                name: "googledoc"
                widget: "string"
                required: true
                hint: "What's the Google Doc link? Make sure it ends in `/mobilebasic`. And make sure it's an archived copy that wont be modified in future."
              # Expired?
              - label: "Expired"
                name: "hidden"
                widget: "boolean"
                default: false
                hint: "Flip this on if this law has been repealed or made obsolete"
              # Content
              - label: "Content"
                name: "body"
                widget: "markdown"
                required: false
                hint: "You do not need to include the title in the body."
  #######################################################
  ## Senate Bills
  #######################################################
  - name: "lawchanges"
    label: "Changes to Law"
    label_singular: "Change to Law"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{headline}}"
    extension: "md"
    format: "yaml-frontmatter"
    editor: { preview: false }
    sortable_fields: ["date"]
    filter: { field: "changetolaw", value: true }
    fields:
      # ChangeToLaw
      - label: "ChangeToLaw"
        name: "changetolaw"
        widget: "hidden"
        required: true
        default: true
      # Layout
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        required: true
        default: "lawchange"
      # Changing institution
      - label: "Institution"
        name: "institution"
        widget: "select"
        required: true
        hint: "Who changed the law?"
        options:
          - {label: "Senate", value: "senate"}
          - {label: "Executive (President, etc)", value: "executive"}
          - {label: "Referendum", value: "referendum"}
          - {label: "Signatures of Icenians", value: "icenian-signatures"}
        default: "senate"
      # Headline
      - label: "Title"
        name: "headline"
        widget: "string"
        required: true
        hint: "The headline to show readers, e.g: Passage of the Bill of Rights"
      # Date
      - label: "When did this change go into effect?"
        name: "date"
        widget: "datetime"
        required: true
        # https://momentjs.com/docs/#/parsing/string-format/
        date_format: "Do MMMM YYYY" # e.g. 1st January 1970
        time_format: "HH:mm" # e.g. 21:07
        format: "YYYY-MM-DD HH:mm:00 Z"
        hint: "Typically it's when the President gave assent."
      # Headline
      - label: "How are you embedding this?"
        name: "document"
        widget: "object"
        required: true
        fields:
          - label: "Type"
            name: "type"
            widget: "select"
            options:
              - {label: "Inline PDF", value: "inline-pdf"}
              - {label: "Local File", value: "local-file"}
              - {label: "Remote File", value: "remote-file"}
            default: ""
          - label: "Value"
            name: "value"
            widget: "string"
            required: true
            hint: "If you're using Inline PDF, please use https://base64.guru/converter/encode/file or other service to generate a base64 string of that PDF and paste it here."
      # Changes
      - label: "Changes to Law"
        name: "changes"
        widget: "list"
        default: []
        summary: "{{target}} ({{kind}})"
        fields:
          - label: "Which Law?"
            name: "target"
            widget: "relation"
            collection: "data"
            search_fields: ["entries.*.name"]
            value_field: "entries.*.slug"
            display_fields: ["entries.*.name"]
            default: ""
            hint: "Just start typing and it'll search for that legislation. Click the correct result. The law file needs to already exist."
          - label: "Change"
            name: "kind"
            widget: "select"
            options:
              - {label: "Passed new law", value: "passage"}
              - {label: "Amended the law", value: "amendment"}
              - {label: "Repealed the law", value: "repeal"}
              - {label: "Made this law obsolete", value: "obsolete"}
            default: ""
        hint: "What does this Bill do in regards to changes to law? Note that Great Repeal Bills, and other wholly 'effecting' Bills, needn't have their own law page, nor include a change here passing themselves."
      # Content
      - label: "Content"
        name: "body"
        widget: "markdown"
        required: false
        hint: "You do not need to include the title in the body."
      # Icon
      - label: "Icon"
        name: "icon"
        widget: "string"
        default: "/assets/images/law_stock.jpeg"
        required: true
        hint: "The image that will appear beside the headline on the news page (default: /assets/images/law_stock.jpeg)"
  #######################################################
  ## Elections
  #######################################################
  - name: "elections"
    label: "Elections"
    label_singular: "Election"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-senate-election"
    identifier_field: "headline"
    description: "NetlifyCMS doesn't support auto-increment yet. You'll need to make sure to enter a properly incremented term number! Best to sort by Term Number in descending order and see the top result."
    extension: "md"
    format: "yaml-frontmatter"
    editor: { preview: false }
    sortable_fields: ["term", "date"]
    filter: { field: "election", value: true }
    fields:
      # IsElection
      - label: "Election"
        name: "election"
        widget: "hidden"
        required: true
        default: true
      # Layout
      - label: "Layout"
        name: "layout"
        widget: "hidden"
        required: true
        default: "term"
      # Headline
      - label: "Headline"
        name: "headline"
        widget: "string"
        hint: "What headline would you give this election? e.g: October Senate (2022)"
      # Term Number
      - label: "Term Number"
        name: "term"
        widget: "number"
        value_type: "int"
        min: 1
        step: 1
      # Date
      - label: "When was the election certified?"
        name: "date"
        widget: "datetime"
        required: true
        # https://momentjs.com/docs/#/parsing/string-format/
        date_format: "Do MMMM YYYY" # e.g. 1st January 1970
        time_format: "HH:mm" # e.g. 21:07
        format: "YYYY-MM-DD HH:mm:00 Z"
      # Custom Parties
      - label: "Parties"
        name: "parties"
        widget: "list"
        default: []
        summary: "{{name}}"
        collapsed: true
        fields:
          - label: "Party Name"
            name: "name"
            widget: "string"
            required: true
            hint: "You should also include a parenthesised acronym / initialism if applicable"
          - label: "Background Colour"
            name: "bgcolour"
            widget: "color"
            allowInput: true
            default: "#A3A3A3"
          - label: "Text Colour"
            name: "txtcolour"
            widget: "color"
            allowInput: true
            default: "#3D3D3D"
          - label: "Current Members"
            name: "members"
            widget: "list"
            allow_add: true
            default: []
          - label: "Former Members"
            name: "exmembers"
            widget: "list"
            allow_add: true
            default: []
            hint: "Any members that left the party during the term."
        hint: "Put the parties in order of campaign annoucement. Independents should always go last."
      # Content
      - label: "Content"
        name: "body"
        widget: "markdown"
        required: false
        hint: "Is there anything you'd like to note down about this term?"
      # Icon
      - label: "Icon"
        name: "icon"
        widget: "string"
        default: "/assets/images/election_stock.png"
        required: true
        hint: "The image that will appear beside the headline on the news page (default: /assets/images/election_stock.png)"
